---
version: '3.8'
services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
    volumes:
      - ./server:/opt/ArmaReforgerServer
      - ./steamcmd:/opt/steamcmd
    environment:
      - ARMA_CONFIG=/opt/ArmaReforgerServer/configs/config.json
      - ARMA_MAX_FPS=60
